# Generated by Django 4.2.14 on 2024-07-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_alter_phonebrand_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='phonebrand',
            name='unique_name_nationality',
        ),
        migrations.AlterUniqueTogether(
            name='phonebrand',
            unique_together={('name', 'nationality')},
        ),
    ]
