# Generated by Django 4.2.14 on 2024-07-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_phonemodel_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together={('brand', 'model')},
        ),
    ]
