# Generated by Django 4.2.14 on 2024-07-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_alter_phonemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('phone_name', 'price', 'color', 'screen_size', 'manufacturing_country')},
        ),
    ]
