# Generated by Django 4.2.14 on 2024-07-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_alter_phone_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-price']},
        ),
    ]
