# Generated by Django 4.2.14 on 2024-07-28 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_alter_phone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(help_text='The currency is the dollar', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(help_text='Screen size in inches', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
    ]
