# Generated by Django 4.2.14 on 2024-07-28 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_alter_phone_price_alter_phone_screen_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(help_text='The currency is the dollar', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
